version: "3"
services:
  app:
    image: sf_data_integration:prod
    build: .
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgres://user:password@prod-db-host/dbname
      - SALESFORCE_CREDENTIALS=/path/to/salesforce_credentials
    volumes:
      - ./sf_data_integration:/app
    ports:
      - "80:5000"
    networks:
      - sf_network
    restart: always

networks:
  sf_network:
    driver: bridge
